version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install requirements_dev.txt
          command: python -m pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: |
            python -m coverage run -m unittest discover
            python -m coverage xml
      - codecov/upload
  publish:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel
      - run:
          name: Install twine
          command: |
            python -m pip install pipenv
            python -m pipenv install twine
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Upload to PyPI
          command: |
            python -m pipenv run twine upload dist/*

workflows:
  test_publish:
    jobs:
      - test
      - publish:
          context:
            - PYPI
          requires:
            - test
          filters:
            branches:
              only:
                - main
