# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_dev.txt
      - run:
          name: Run tests
          command: |
            coverage run -m unittest discover
            coverage xml
      - codecov/upload

workflows:
  sample:
    jobs:
      - test
